"""
Streamlit Dashboard - skinessentialsbyher.com
Auto-generated by Data Analyst Agent

Run with: streamlit run dashboard_skinessentialsbyher.com_20260226.py
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from datetime import datetime

# Page config
st.set_page_config(
    page_title="skinessentialsbyher.com Analytics Dashboard",
    page_icon="📊",
    layout="wide",
)

# Custom CSS for better styling
st.markdown(
    """
<style>
    .main {
        background-color: #f5f5f5;
    }
    .stMetric {
        background-color: white;
        padding: 15px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .recommendation-box {
        background-color: #fff3cd;
        border-left: 4px solid #ffc107;
        padding: 15px;
        margin: 10px 0;
        border-radius: 5px;
    }
    .insight-box {
        background-color: #d1ecf1;
        border-left: 4px solid #17a2b8;
        padding: 10px;
        margin: 5px 0;
        border-radius: 5px;
    }
    .good-metric { color: #28a745; }
    .warning-metric { color: #ffc107; }
    .bad-metric { color: #dc3545; }
</style>
""",
    unsafe_allow_html=True,
)

# Title
st.title("📊 skinessentialsbyher.com Analytics Dashboard")
st.markdown(
    f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')} | **Period:** Last 30 days"
)
st.markdown("---")

# ==================== TREND SECTION ====================
# Note: trend_indicator is set earlier in the Python code

# ==================== OVERVIEW SECTION ====================
st.header("🎯 Performance Overview")

col1, col2, col3, col4 = st.columns(4)

overall_score = 46.9
with col1:
    st.metric(
        "Overall Score",
        f"{overall_score}/100",
        delta="Excellent"
        if float(overall_score) >= 80
        else "Good"
        if float(overall_score) >= 60
        else "Needs Work",
    )

with col2:
    st.metric("Search Visibility", "13.5/100")

with col3:
    st.metric("GA4 Performance", "38.9/100")

with col4:
    st.metric("Meta Performance", "50.0/100")

# Score explanation
with st.expander("📖 Understanding the Scores"):
    st.markdown("""
    - **Overall Score**: Weighted average of all channels (GSC 20%, GA4 30%, Meta 20%, Technical 15%, Content 15%)
    - **Search Visibility**: Based on clicks, impressions, and ranking positions
    - **GA4 Performance**: Based on sessions, bounce rate, and conversions
    - **Meta Performance**: Based on impressions and engagement rate
    """)

st.markdown("---")

# ==================== GSC SECTION ====================
st.header("🔍 Google Search Console (SEO)")

# GSC Metrics
col_g1, col_g2, col_g3, col_g4 = st.columns(4)
with col_g1:
    st.metric("Total Clicks", "0")
with col_g2:
    st.metric("Total Impressions", "18")
with col_g3:
    ctr = gsc.get("average_ctr", 0)
    ctr_display = f"{ctr:.2%}"
    st.metric(
        "Average CTR", ctr_display, delta="Good" if ctr > 0.05 else "Needs Improvement"
    )
with col_g4:
    pos = gsc.get("average_position", 0)
    st.metric(
        "Avg Position",
        f"{pos:.1f}",
        delta="Good" if pos <= 3 else None,
        delta_color="inverse",
    )

# GSC Insights
st.markdown("### 💡 Insights")
if gsc.get("total_clicks", 0) < 100:
    st.markdown(
        f"""
    <div class="insight-box">
    <b>⚠️ Low Search Traffic:</b> Only {gsc.get("total_clicks", 0)} clicks in the last 30 days. 
    This indicates your SEO strategy needs significant improvement. Focus on ranking for relevant keywords.
    </div>
    """,
        unsafe_allow_html=True,
    )
else:
    st.markdown(
        f"""
    <div class="insight-box">
    <b>✅ Good Search Traffic:</b> {gsc.get("total_clicks", 0)} clicks shows decent search visibility.
    </div>
    """,
        unsafe_allow_html=True,
    )

# GSC Top Queries
if gsc.get("top_queries"):
    st.markdown("### 📋 Top Performing Queries")
    queries_data = []
    for q in gsc.get("top_queries", [])[:10]:
        queries_data.append(
            {
                "Query": q.get("keys", [""])[0],
                "Clicks": q.get("clicks", 0),
                "Impressions": q.get("impressions", 0),
                "CTR": f"{q.get('ctr', 0):.1%}",
                "Position": q.get("position", 0),
            }
        )
    st.dataframe(pd.DataFrame(queries_data), use_container_width=True)

# GSC Recommendations
st.markdown("### 🎯 Recommendations for SEO")
for rec in gsc_recs:
    priority_color = (
        "#dc3545"
        if rec["priority"] == "High"
        else "#ffc107"
        if rec["priority"] == "Medium"
        else "#28a745"
    )
    st.markdown(
        f"""
    <div class="recommendation-box">
        <b style="color:{priority_color}">[{rec["priority"].upper()}]</b> <b>{rec["title"]}</b><br>
        {rec["description"]}
    </div>
    """,
        unsafe_allow_html=True,
    )

st.markdown("---")

# ==================== GA4 SECTION ====================
st.header("📊 Google Analytics 4 (Web Analytics)")

# GA4 Metrics
col_ga1, col_ga2, col_ga3, col_ga4 = st.columns(4)
with col_ga1:
    st.metric("Sessions", "27")
with col_ga2:
    st.metric("Users", "22")
with col_ga3:
    br = ga4.get("bounce_rate", 0)
    st.metric(
        "Bounce Rate",
        f"{br:.1%}",
        delta="Good" if br < 0.4 else "Needs Improvement",
        delta_color="inverse",
    )
with col_ga4:
    st.metric("Conversions", "0")

# GA4 Insights
st.markdown("### 💡 Insights")
if ga4.get("bounce_rate", 0) > 0.5:
    st.markdown(
        f"""
    <div class="insight-box">
    <b>⚠️ High Bounce Rate:</b> {ga4.get("bounce_rate", 0):.1%} of visitors leave without engaging.
    This suggests issues with page content, load time, or user experience.
    </div>
    """,
        unsafe_allow_html=True,
    )

if ga4.get("conversions", 0) == 0:
    st.markdown(
        f"""
    <div class="insight-box">
    <b>⚠️ No Conversions:</b> Zero conversions in the last 30 days. 
    Review your CTAs and conversion funnel.
    </div>
    """,
        unsafe_allow_html=True,
    )

# GA4 Device Breakdown
if ga4.get("device_breakdown"):
    st.markdown("### 📱 Device Breakdown")
    device_data = pd.DataFrame(
        list(ga4.get("device_breakdown", {}).items()), columns=["Device", "Sessions"]
    )
    fig = px.pie(
        device_data,
        values="Sessions",
        names="Device",
        title="Sessions by Device Type",
        color_discrete_sequence=px.colors.qualitative.Set2,
    )
    st.plotly_chart(fig, use_container_width=True)

# GA4 Source Breakdown
if ga4.get("source_breakdown"):
    st.markdown("### 🌐 Traffic Sources")
    source_data = ga4.get("source_breakdown", {})
    sorted_sources = dict(
        sorted(source_data.items(), key=lambda x: x[1], reverse=True)[:5]
    )
    source_df = pd.DataFrame(
        list(sorted_sources.items()), columns=["Source", "Sessions"]
    )
    fig2 = px.bar(
        source_df,
        x="Source",
        y="Sessions",
        title="Top 5 Traffic Sources",
        color="Sessions",
        color_continuous_scale="Blues",
    )
    st.plotly_chart(fig2, use_container_width=True)

# GA4 Recommendations
st.markdown("### 🎯 Recommendations for GA4")
for rec in ga4_recs:
    priority_color = (
        "#dc3545"
        if rec["priority"] == "High"
        else "#ffc107"
        if rec["priority"] == "Medium"
        else "#28a745"
    )
    st.markdown(
        f"""
    <div class="recommendation-box">
        <b style="color:{priority_color}">[{rec["priority"].upper()}]</b> <b>{rec["title"]}</b><br>
        {rec["description"]}
    </div>
    """,
        unsafe_allow_html=True,
    )

st.markdown("---")

# ==================== META SECTION ====================
st.header("📱 Meta/Facebook Insights")

# Meta Metrics
col_m1, col_m2, col_m3, col_m4 = st.columns(4)
with col_m1:
    st.metric("Impressions", "380,797")
with col_m2:
    st.metric("Page Fans", "61,830")
with col_m3:
    er = meta.get("engagement_rate", 0)
    st.metric(
        "Engagement Rate",
        f"{er:.2%}",
        delta="Good" if er > 0.03 else "Needs Improvement",
    )
with col_m4:
    st.metric("Avg Daily Impressions", "54,399")

# Meta Insights
st.markdown("### 💡 Insights")
if meta.get("engagement_rate", 0) > 0.03:
    st.markdown(
        f"""
    <div class="insight-box">
    <b>✅ Good Engagement:</b> {meta.get("engagement_rate", 0):.2%} engagement rate is above average.
    Your audience is actively interacting with your content.
    </div>
    """,
        unsafe_allow_html=True,
    )
else:
    st.markdown(
        f"""
    <div class="insight-box">
    <b>⚠️ Low Engagement:</b> {meta.get("engagement_rate", 0):.2%} engagement rate is below average.
    Consider posting more engaging content types (videos, polls, questions).
    </div>
    """,
        unsafe_allow_html=True,
    )

# Meta Recommendations
st.markdown("### 🎯 Recommendations for Meta")
for rec in meta_recs:
    priority_color = (
        "#dc3545"
        if rec["priority"] == "High"
        else "#ffc107"
        if rec["priority"] == "Medium"
        else "#28a745"
    )
    st.markdown(
        f"""
    <div class="recommendation-box">
        <b style="color:{priority_color}">[{rec["priority"].upper()}]</b> <b>{rec["title"]}</b><br>
        {rec["description"]}
    </div>
    """,
        unsafe_allow_html=True,
    )

st.markdown("---")

# ==================== SUMMARY ====================
st.header("📈 Action Summary")

st.markdown("""
### Quick Wins (Implement This Week)
1. **Fix High Bounce Rate** - Improve page load speed and content quality
2. **Optimize for Top 3 Positions** - Target keywords where you rank 4-10
3. **Increase Posting Frequency** - Post 3-5 times per week on Meta

### Medium-Term Goals (Next 30 Days)
1. **Add Conversion Tracking** - Set up goals in GA4
2. **Create Video Content** - Higher engagement on Meta
3. **Build Backlinks** - Improve domain authority for SEO

### Long-Term Strategy
1. **Content Marketing** - Create pillar pages for main keywords
2. **Email List Growth** - Capture visitors for nurturing
3. **Paid Promotion** - Consider Facebook Ads for reach
""")

# Footer
st.markdown("---")
st.markdown("*Dashboard generated by Data Analyst Agent | For internal use only*")
