import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import datetime

st.set_page_config(
    page_title="skinessentialsbyher.com Analytics", page_icon="📊", layout="wide"
)

st.title("📊 skinessentialsbyher.com Analytics Dashboard")
st.markdown(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")

# Data from our analysis
gsc_data = {
    "total_clicks": 3,
    "total_impressions": 73,
    "average_ctr": 4.11,
    "average_position": 8.7,
}

ga4_data = {
    "total_sessions": 54,
    "total_users": 45,
    "bounce_rate": 58.0,
    "conversions": 0,
}

meta_data = {
    "total_impressions": 351991,
    "total_engaged_users": 17599,
    "total_fans": 61892,
    "engagement_rate": 5.00,
}

# Overview metrics
col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Overall Score", "51.3/100")
with col2:
    st.metric("Search Visibility", "30.8/100")
with col3:
    st.metric("GA4 Performance", "42.0/100")

st.markdown("---")

# GSC Section
st.header("🔍 Google Search Console (SEO)")
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total Clicks", gsc_data["total_clicks"])
with col2:
    st.metric("Total Impressions", gsc_data["total_impressions"])
with col3:
    st.metric("Average CTR", f"{gsc_data['average_ctr']}%")
with col4:
    st.metric("Avg Position", gsc_data["average_position"])

# GA4 Section
st.header("📊 Google Analytics 4 (Web Analytics)")
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Sessions", ga4_data["total_sessions"])
with col2:
    st.metric("Users", ga4_data["total_users"])
with col3:
    st.metric("Bounce Rate", f"{ga4_data['bounce_rate']}%")
with col4:
    st.metric("Conversions", ga4_data["conversions"])

# Meta Section
st.header("📱 Meta/Facebook Insights")
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total Impressions", f"{meta_data['total_impressions']:,}")
with col2:
    st.metric("Page Fans", f"{meta_data['total_fans']:,}")
with col3:
    st.metric("Engagement Rate", f"{meta_data['engagement_rate']}%")
with col4:
    st.metric("Engaged Users", f"{meta_data['total_engaged_users']:,}")

st.markdown("---")
st.markdown("### 📈 Key Insights")
st.markdown("""
- **SEO Opportunity**: Average position 8.7 - room for improvement to reach top 3
- **High Bounce Rate**: 58% bounce rate indicates need for better content relevance
- **Strong Social Presence**: 61,892 followers with good engagement rate (5%)
""")

st.markdown("---")
st.markdown("*Dashboard generated by Data Analyst Agent | For internal use only*")
